version: 2

models:
  - name: garmin_stress
    description: "Description of your garmin_stress table (modify as needed)."
    columns:
      - name: userprofilepk
        description: "From deserializer."
        tests:
          - not_null

      - name: calendardate
        description: "From deserializer."
        tests:
          - not_null
          - is_date

      - name: starttimestampgmt
        description: "From deserializer."
        tests:
          - not_null
          - is_timestamp

      - name: endtimestampgmt
        description: "From deserializer."
        tests:
          - not_null
          - is_timestamp

      - name: starttimestamplocal
        description: "From deserializer."
        tests:
          - not_null
          - is_timestamp

      - name: endtimestamplocal
        description: "From deserializer."
        tests:
          - not_null
          - is_timestamp

      - name: maxstresslevel
        description: "From deserializer."
        tests:
          - not_null

      - name: avgstresslevel
        description: "From deserializer."
        tests:
          - not_null

      - name: stresschartvalueoffset
        description: "From deserializer."
        tests:
          - not_null

      - name: stresschartyaxisorigin
        description: "From deserializer."
        tests:
          - not_null

      - name: stressvaluedescriptorsdtolist
        description: "From deserializer."

      - name: stressvaluesarray
        description: "From deserializer."

      - name: bodybatteryvaluedescriptorsdtolist
        description: "From deserializer."

      - name: bodybatteryvaluesarray
        description: "From deserializer."

      - name: year
        description: "Partitioned by year."
        tests:
          - not_null

      - name: month
        description: "Partitioned by month."
        tests:
          - not_null

      - name: day
        description: "Partitioned by day."
        tests:
          - not_null