version: 2

sources:
  - name: garmin
    database: awsdatacatalog
    schema: default
    tables:
      - name: garmin_stress
        identifier: garmin_stress
      - name: garmin_sleep
        identifier: garmin_sleep